name: Create benchmark
run-name: Benchmark
on:
  workflow_dispatch:

jobs:
  benchmark:
    name: Create benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4
      - name: Install uv with Python version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies with uv
        run: uv pip install -r pyproject.toml --extra benchmark
      - name: Run benchmarks
        run: python benchmark/perform_benchmark.py
      - name: Remove pyc files
        run: rm -f */*.pyc
      - name: Push to github
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "benchmark updated"
          git push
