name: Create benchmark
run-name: Benchmark
on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Install prettytable
        run: python -m pip install prettytable
      - name: Run benchmarks
        run: python benchmark/perform_benchmark.py
      - name: Remove pyc files
        run: rm -f */*.pyc
      - name: Push to github
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "benchmark updated"
          git push
