name: Create release
run-name: Automatic release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    permissions:
      id-token: write
    concurrency: release
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - name: Install uv with Python version 3.13
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.13
      - run: |
          uv venv --python 3.13
          uv pip install --upgrade build
          uv run python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
